---
- name: Create user with sudo privilidges
  user:
    name: "{{ user_to_create }}"
    append: true
    groups:
      - sudo
    password: '{{ "pass" | password_hash("sha512") }}'
    update_password: on_create
    shell: '/usr/bin/bash'
    generate_ssh_key: true
    ssh_key_bits: 4096
# - name: Copy repository into user's home directory
#   copy:
#     src: /root/ansible-pc/
#     dest: /home/qubetzl/ansible-pc/
#     remote_src: true
#     owner: "{{ user_to_create }}"
#     group: "{{ user_to_create }}"
#     mode: 'u=rwx,g=r,o=r'
